### ISSUE TITLE
Chrome webstore link not working, 404 error

### ISSUE THREAD

**Issue by j-falk** [wearerequired/harvest-chrome#10]
https://chrome.google.com/webstore/detail/required-time-tracker-for/molohbmpdeahlajdfnjppdlbbbgbbgca gives a 404 error message. Has the extension been removed for any reason? What would be the preferred way to install it now?

Appreciate all the help with this since we have been using this extension for its Helpscout support 🙌

**Comment by derpaschi** [comment]
Hi @j-falk - unfortunately, we've had to set the extension to private as it was not compliant with Google guidelines anymore.

**Comment by j-falk** [comment]
Ok, I understand. What would you say would be the preferred way to use the extension? I managed to get it working using the steps provided here, https://bashvlas.com/blog/install-chrome-extension-in-developer-mode/, but maybe is there a better way to be able to use it?

**Comment by derpaschi** [comment]
> Ok, I understand. What would you say would be the preferred way to use the extension? I managed to get it working using the steps provided here, https://bashvlas.com/blog/install-chrome-extension-in-developer-mode/, but maybe is there a better way to be able to use it?

I think that's the way to go.
