### ISSUE TITLE
Refused to connect to 'https://platform.harvestapp.com

### ISSUE THREAD

**Issue by grappler** [wearerequired/harvest-chrome#2]
I am not sure why there are errors in the console. It is only on Helpscout.

> [Report Only] Refused to connect to 'https://platform.harvestapp.com/platform/running_timer.json' because it violates the following Content Security Policy directive: "connect-src 'self' 'unsafe-inline' api.mixpanel.com app.getsentry.com https://*.ipify.org https://*.pusher.com wss://ws-helpscout.pusher.com:* bam.nr-data.net *.wistia.com *.akamaihd.net *.drift.com https://sentry.io *.mxpnl.net *.fullstory.com risk.clearbit.com js.hs-scripts.com js.leadin.com forms.hubspot.com docsapi.helpscout.net helpscout.helpscoutdocs.com".

**Comment by ocean90** [comment]
The headers have been adjusted so the modal and the timer is now working. There is still one warning though:

```
Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1…RsLmhpZGUuZW5kID09PSAnZnVuY3Rpb24nICkgewoJCWRsLmhpZGUuZW5kKCk7Cgl9Cn0pKCk7' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.google-analytics.com https://*.nr-data.net https://ajax.googleapis.com cache.harvestapp.com https://js-agent.newrelic.com https://js.appcenter.intuit.com https://platform.twitter.com https://www.google.com https://www.googleadservices.com https://www.googletagmanager.com https://connect.facebook.net".
```

Not sure why that is an data URI, but the code behind the URI is:

```js
(function() {
	var noopfn = function() {
	};
	var w = window;
	w.ga = w.ga || noopfn;
	var dl = w.dataLayer;
	if ( dl instanceof Object && dl.hide instanceof Object && typeof dl.hide.end === 'function' ) {
		dl.hide.end();
	}
})();
```

Seems to be related to Google Analytics.

**Comment by grappler** [comment]
I don't have an issue on my end.

**Comment by grappler** [comment]
This is fixed now.

**Comment by ocean90** [comment]
@grappler Happens only if the uBlock Origin (ad blocker) extension is active.
