### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by grappler** [wearerequired/harvest-chrome#3]
`git clone git@github.com:wearerequired/harvest-chrome.git` to any location

This is how you load a dev chrome extension, https://developer.chrome.com/extensions/getstarted#unpacked

After making changes click the "Reload" button for the extention in `chrome://extensions`

Or from the repo: https://chrome.google.com/webstore/detail/required-time-tracker-for/molohbmpdeahlajdfnjppdlbbbgbbgca

**Comment by ocean90** [comment]
@grappler Can you add the new install link to the readme or meta data?

**Comment by grappler** [comment]
@ocean90 I have added it as the projects URL. https://chrome.google.com/webstore/detail/required-time-tracker-for/molohbmpdeahlajdfnjppdlbbbgbbgca
