### ISSUE TITLE
Add icon when the conversation is loaded via JS

### ISSUE THREAD

**Issue by grappler** [wearerequired/harvest-chrome#4]
When you are in a mailbox e.g. https://secure.helpscout.net/mailbox/f5eb78b53f1e4ae3/330332/ you click on a conversation it will show without the page needing to reload. The URL is automatically updated.

At this point the icon will not show. When you refresh the page it shows.

Any ideas how to solve this and where to add the code?

**Comment by ocean90** [comment]
You could use jQuery's `.ajaxComplete()` method to register a handler that checks the current page and adds the button if it's a single thread.

**Comment by grappler** [comment]
I need to add an event but I am not sure how. I was testing with something like:

```js
return window.addEventListener("message", (function(_this) {
    return function(event) {
      if (event.data.helpscoutUrlChanged == null) {
        return;
      }
      return _this.addTimerIfOnIssue();
    };
})(this));
```
