### ISSUE TITLE
Time Tracking im Notion

### ISSUE THREAD

**Issue by codiina** [wearerequired/harvest-chrome#8]
Falls möglich, wärs angenehm auch aus dem Notion direkt ein Time Tracker zu haben.

Kommentar von Ulrich:
> Im Browser ist es sicher möglich. Wir könnten sicher unser Browser Extension erweitern. Wenn du ein Vorschlag hast wo das Button hin kommen soll, dann kannst du gerne eine Issue machen.
> Ich weiss nicht ob es möglich ist Extensions für Electon Apps zu erstellen.

Ich habe mir das so vorgestellt: 

![Harvest_im_Notion](https://user-images.githubusercontent.com/28655004/102788378-d60ef700-43a2-11eb-9142-50d49750d7e4.jpg)

**Comment by grappler** [comment]
Danke @codiina! Im Screenshot, hast du das Button als HTML im Browser eingefügt oder nur das Bild über den Screenshot gelegt?

**Comment by codiina** [comment]
@grappler Screenshot über Screenshot im Figma 🙃

**Comment by grappler** [comment]
Hier ist eine Möglichkeit Notion Desktop zu erweitern: https://github.com/notion-enhancer/notion-enhancer

Notion Browser extentions
- https://github.com/GorvGoyl/Notion-Boost-browser-extension
- https://github.com/scarsu/NotionX
